// @generated by protobuf-ts 2.9.3
// @generated from protobuf file "mobile.proto" (package "mobile", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Mobile } from "./mobile";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { WireguardConfigResponse } from "./mobile";
import type { WireguardConfigRequest } from "./mobile";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service mobile.Mobile
 */
export interface IMobileClient {
    /**
     * @generated from protobuf rpc: GetWireguardConfig(mobile.WireguardConfigRequest) returns (mobile.WireguardConfigResponse);
     */
    getWireguardConfig(input: WireguardConfigRequest, options?: RpcOptions): UnaryCall<WireguardConfigRequest, WireguardConfigResponse>;
}
/**
 * @generated from protobuf service mobile.Mobile
 */
export class MobileClient implements IMobileClient, ServiceInfo {
    typeName = Mobile.typeName;
    methods = Mobile.methods;
    options = Mobile.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetWireguardConfig(mobile.WireguardConfigRequest) returns (mobile.WireguardConfigResponse);
     */
    getWireguardConfig(input: WireguardConfigRequest, options?: RpcOptions): UnaryCall<WireguardConfigRequest, WireguardConfigResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<WireguardConfigRequest, WireguardConfigResponse>("unary", this._transport, method, opt, input);
    }
}
