// @generated by protobuf-ts 2.9.1
// @generated from protobuf file "mobile.proto" (package "mobile", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message mobile.WireguardConfigRequest
 */
export interface WireguardConfigRequest {
}
/**
 * @generated from protobuf message mobile.WireguardConfigResponse
 */
export interface WireguardConfigResponse {
    /**
     * @generated from protobuf field: string base64Image = 1;
     */
    base64Image: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class WireguardConfigRequest$Type extends MessageType<WireguardConfigRequest> {
    constructor() {
        super("mobile.WireguardConfigRequest", []);
    }
    create(value?: PartialMessage<WireguardConfigRequest>): WireguardConfigRequest {
        const message = {};
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<WireguardConfigRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WireguardConfigRequest): WireguardConfigRequest {
        return target ?? this.create();
    }
    internalBinaryWrite(message: WireguardConfigRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mobile.WireguardConfigRequest
 */
export const WireguardConfigRequest = new WireguardConfigRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class WireguardConfigResponse$Type extends MessageType<WireguardConfigResponse> {
    constructor() {
        super("mobile.WireguardConfigResponse", [
            { no: 1, name: "base64Image", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<WireguardConfigResponse>): WireguardConfigResponse {
        const message = { base64Image: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<WireguardConfigResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: WireguardConfigResponse): WireguardConfigResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string base64Image */ 1:
                    message.base64Image = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: WireguardConfigResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string base64Image = 1; */
        if (message.base64Image !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.base64Image);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message mobile.WireguardConfigResponse
 */
export const WireguardConfigResponse = new WireguardConfigResponse$Type();
/**
 * @generated ServiceType for protobuf service mobile.Mobile
 */
export const Mobile = new ServiceType("mobile.Mobile", [
    { name: "GetWireguardConfig", options: {}, I: WireguardConfigRequest, O: WireguardConfigResponse }
]);
